import { useForm } from "@inertiajs/react";
import { CheckCircle2, Search, XCircle } from "lucide-react";
import { useTranslation } from "react-i18next";
import PublicLayout from "../../Layouts/PublicLayout";

export default function Tracking({ ticket = "", tracking }) {
    const { t } = useTranslation();
    const { data, setData, get, processing, errors } = useForm({ ticket });
    const handleSubmit = (event) => { event.preventDefault(); get(route("public.tracking"), { preserveState: true, replace: true }); };
    return <PublicLayout><section className="public-container public-page-section"><div className="public-tracking-card"><h1>{t("Complaint Tracking")}</h1><p>{t("Check the latest status of your complaint without signing in.")}</p><form onSubmit={handleSubmit} className="public-tracking-form"><div><label>{t("Complaint Ticket Number")}</label><input className={`form-control ${errors.ticket ? "is-invalid" : ""}`} value={data.ticket} onChange={(event) => setData("ticket", event.target.value)} placeholder="WBS-2026-0001" />{errors.ticket && <div className="invalid-feedback">{errors.ticket}</div>}</div><button className="btn public-primary-button" disabled={processing} type="submit"><Search size={17} /> {t("Search")}</button></form>{ticket && !tracking && <div className="alert alert-warning mt-4">{t("Complaint ticket was not found.")}</div>}{tracking && <div className="public-tracking-result mt-4"><div className="d-flex justify-content-between align-items-center"><div><span className="public-label">{t("Ticket Number")}</span><h3>{tracking.ticket_number}</h3></div><span className="public-status"><CheckCircle2 size={16} /> {t(tracking.status)}</span></div><div className="public-tracking-meta"><div><span>{t("Category")}</span><strong>{tracking.category || "-"}</strong></div><div><span>{t("Submitted At")}</span><strong>{tracking.submitted_at ? new Date(tracking.submitted_at).toLocaleString() : "-"}</strong></div></div><div className="public-timeline">{tracking.histories.map((history, index) => <div className="public-timeline-item" key={`${history.created_at}-${index}`}><span className="public-timeline-dot">{index === 0 ? <CheckCircle2 size={15} /> : <XCircle size={15} />}</span><div><strong>{t(history.status)}</strong><small>{history.created_at ? new Date(history.created_at).toLocaleString() : "-"}</small></div></div>)}</div></div>}</div></section></PublicLayout>;
}
